import java.lang.Exception

fun main() {











}